apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
    service.type: http
  {{- with .Values.service.main.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.main.type }}
  ports:
    - port: {{ .Values.service.main.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.dns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-dns
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
    service.type: dns
  {{- with .Values.service.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
  {{- if .Values.service.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.dns.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.dns.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.dns.externalTrafficPolicy }}
  {{- end }}
  ports:
    {{- if .Values.service.dns.ports.tcp.enabled }}
    - port: {{ .Values.service.dns.ports.tcp.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    {{- end }}
    {{- if .Values.service.dns.ports.udp.enabled }}
    - port: {{ .Values.service.dns.ports.udp.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    {{- end }}
    {{- if .Values.service.dns.ports.tls.enabled }}
    - port: {{ .Values.service.dns.ports.tls.port }}
      targetPort: dns-over-tls
      protocol: TCP
      name: dns-over-tls
    {{- end }}
    {{- if .Values.service.dns.ports.quic.enabled }}
    - port: {{ .Values.service.dns.ports.quic.port }}
      targetPort: dns-over-quic
      protocol: UDP
      name: dns-over-quic
    {{- end }}
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
{{- end }}
