apiVersion: v2
name: adguard-home
description: Free and open source, powerful network-wide ads & trackers blocking DNS server.
home: https://github.com/AdguardTeam/AdGuardHome
icon: https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/client/public/favicon.png
type: application
version: 1.0.0
# renovate datasource=docker depName=adguard/adguardhome
appVersion: v0.107.56
kubeVersion: ">=1.22.0-0"
keywords:
  - adblock
  - dns
  - privacy
  - adguard
sources:
  - https://github.com/AdguardTeam/AdGuardHome
maintainers:
  - name: tideline3d
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Refactored to standalone chart without dependencies, added 3 replicas and MetalLB support
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/AdguardTeam/AdGuardHome
