apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "adguard-home.fullname" . }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "adguard-home.fullname" . }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "adguard-home.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "adguard-home.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adguard-home.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.config }}
      initContainers:
        - name: copy-default-config
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              if [[ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]]; then
                mkdir -p /opt/adguardhome/conf
                cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
              fi
          volumeMounts:
            - name: default-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /opt/adguardhome/conf
            {{- end }}
          securityContext:
            runAsUser: 0
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-over-tls
              containerPort: 853
              protocol: TCP
            - name: dns-over-quic
              containerPort: 784
              protocol: UDP
          livenessProbe:
            exec:
              command:
                - nslookup
                - google.com
                - 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - nslookup
                - google.com
                - 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: /opt/adguardhome/conf
            {{- end }}
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: /opt/adguardhome/work
            {{- end }}
            {{- if .Values.config }}
            - name: default-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            {{- end }}
      volumes:
        {{- if .Values.config }}
        - name: default-config
          configMap:
            name: {{ include "adguard-home.configMapName" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          {{- if .Values.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ include "adguard-home.name" . }}
                topologyKey: kubernetes.io/hostname
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "adguard-home.name" . }}
              topologyKey: kubernetes.io/hostname
          {{- end }}
      {{- end }}
  volumeClaimTemplates:
  {{- if .Values.persistence.config.enabled }}
  - metadata:
      name: config
      labels:
        {{- include "adguard-home.labels" . | nindent 8 }}
        pvc.type: config
      {{- with .Values.persistence.config.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.config.accessMode | default "ReadWriteOnce" }}
      resources:
        requests:
          storage: {{ .Values.persistence.config.size | default "1Gi" }}
      {{- if .Values.persistence.config.storageClass }}
      {{- if (eq "-" .Values.persistence.config.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.config.storageClass }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- if .Values.persistence.data.enabled }}
  - metadata:
      name: data
      labels:
        {{- include "adguard-home.labels" . | nindent 8 }}
        pvc.type: data
      {{- with .Values.persistence.data.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.data.accessMode | default "ReadWriteOnce" }}
      resources:
        requests:
          storage: {{ .Values.persistence.data.size | default "4Gi" }}
      {{- if .Values.persistence.data.storageClass }}
      {{- if (eq "-" .Values.persistence.data.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.data.storageClass }}
      {{- end }}
      {{- end }}
  {{- end }}
